language: node_js
notifications:
  email:
    on_failure: always
node_js:
  - '10.16.0'
script:
  - npm run build
  - npm test
deploy:
  provider: pages:git
  edge: true # opt in to dpl v2
  repo: trmapi/trmapi.github.io
  local_dir: build
  target_branch: master
  on:
    branch: master
after_success:
  - npx semantic-release
